#!/bin/bash

# Project 1: A menu driven program, designed to allow the user to select which system information they wish to view.

echo "		System View		

1. View all regular users on the system

2. View your PID

3. Check the available disk space

4. View group membership of the current user

5. Quit the program
"

# Functions
view_users () {						# Displays all regular users
	awk -F: '$3 >= 1000 {print $1}' /etc/passwd	
}

view_pid () {						# Displays current user PID
	id -u
	echo "You are user: $USER"
}

disk_space () {						# Show amount of disk space used/free
	df -h
}

view_groups () {					# View group membership of current user
	groups
}

quit () {						# Quit the program
	quit_time=3
	while [[ "$quit_time" -ne 0 ]]; do
		echo "Exiting in $quit_time"
		quit_time=$((quit_time - 1))
		sleep 1
	done

	printf "\n"
	echo "Thanks for using us! Goodbye!"
	exit 1
}

# Main Program Loop
while [[ "$menu_option" -ne 5 ]]; do
	read -p "Enter here: " menu_option
	case "$menu_option" in
		1)	printf "\n"						# Menu option 1
			echo "Displaying all regular users on the system:"
			printf "\n"
			view_users
			printf "\n"
			;;

		2)	printf "\n"						# Menu option 2
			user_id=$(view_pid)
			echo "Your PID is: $user_id"
			printf "\n"
			;;
			
		3)	printf "\n"						# Menu option 3
			echo "		Disk Space Available 		"
			printf "\n"
			disk_space
			printf "\n"
			;;

		4)	printf "\n"						# Menu option 4
			echo "		$USER's Group Membership	"
			printf "\n"
			view_groups
			printf "\n"
			;;
			
		5)	printf "\n"						# Menu option 5
			echo "Quitting the Program"
			printf "\n"
			quit
			;;
	esac
done
