#!/bin/bash

#Read in a name and display it back to the user


#Functions
first_name () {
	read -p "Enter your first name: " name
	return
}

last_name () {
	read -p "Enter your last name: " lname
	return
}

#Main Program
first_name
last_name

echo "Your name is $name $lname"
