#!/bin/bash

#Read in a name and display it back to the user

#Functions
first_name () {						#Get the users first name
	read -p "Enter your first name: " fname
	return
}	

last_name () {						#Get the users last name
	read -p "Enter your last name: " lname
	return
}

capture_output () {				#Capture a listing of the directory to a text file
	ls -l > output.txt
	mv output.txt ../Practice
}

#Main Program
first_name
last_name

if [[ -z "$fname" || -z "$lname" ]]; then	#Check if a first name or last name is provided
	echo "No name provided"
	exit 1
fi

echo "Your name is $fname $lname"		#Display the users name back to them

#capture_output

